package com.lei.dao;

import com.lei.model.ChapterIdiom;
import java.util.List;

public interface ChapterIdiomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_idiom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_idiom
     *
     * @mbggenerated
     */
    int insert(ChapterIdiom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_idiom
     *
     * @mbggenerated
     */
    ChapterIdiom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_idiom
     *
     * @mbggenerated
     */
    List<ChapterIdiom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_idiom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChapterIdiom record);
}