package com.lei.dao;

import com.lei.model.Idiom;
import java.util.List;

public interface IdiomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbggenerated
     */
    int insert(Idiom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbggenerated
     */
    Idiom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbggenerated
     */
    List<Idiom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idiom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Idiom record);
}