package com.lei.model;

import java.io.Serializable;

public class ChapterIdiom implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_idiom.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_idiom.idiom_id
     *
     * @mbggenerated
     */
    private String idiomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_idiom.chapter_id
     *
     * @mbggenerated
     */
    private String chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chapter_idiom
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_idiom.id
     *
     * @return the value of chapter_idiom.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_idiom.id
     *
     * @param id the value for chapter_idiom.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_idiom.idiom_id
     *
     * @return the value of chapter_idiom.idiom_id
     *
     * @mbggenerated
     */
    public String getIdiomId() {
        return idiomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_idiom.idiom_id
     *
     * @param idiomId the value for chapter_idiom.idiom_id
     *
     * @mbggenerated
     */
    public void setIdiomId(String idiomId) {
        this.idiomId = idiomId == null ? null : idiomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_idiom.chapter_id
     *
     * @return the value of chapter_idiom.chapter_id
     *
     * @mbggenerated
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_idiom.chapter_id
     *
     * @param chapterId the value for chapter_idiom.chapter_id
     *
     * @mbggenerated
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId == null ? null : chapterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_idiom
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", idiomId=").append(idiomId);
        sb.append(", chapterId=").append(chapterId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}